asset_template = {'name': 'assetName',
 'children': [{'children': [{'name': 'abc'},
                            {'name': 'audio'},
                            {'name': 'comp'},
                            {'name': 'desk'},
                            {'name': 'flip'},
                            {'name': 'geo'},
                            {'name': 'hdz'},
                            {'name': 'render'},
                            {'name': 'scripts'},
                            {'name': 'sim'},
                            {'name': 'tex'},
                            {'name': 'video'},
                            {'name': 'workFiles'}],
               'name': 'houdini'},
              {'children': [{'children': [{'name': 'alembic'},
                                          {'name': 'bifrost'},
                                          {'name': 'nCache'},
                                          {'name': 'particles'}],
                             'name': 'cache'},
                            {'name': 'data'},
                            {'name': 'images'},
                            {'name': 'movies'},
                            {'children': [{'children': [{'name': 'assetLayout'},
                                                        {'name': 'cloth'},
                                                        {'name': 'dressing'},
                                                        {'name': 'groom'},
                                                        {'name': 'lookdev'},
                                                        {'name': 'modeling'},
                                                        {'name': 'rig'}],
                                           'name': 'edit'},
                                          {'children': [{'name': 'assetLayout'},
                                                        {'name': 'cloth'},
                                                        {'name': 'dressing'},
                                                        {'name': 'groom'},
                                                        {'name': 'lightRig'},
                                                        {'name': 'lookdev'},
                                                        {'name': 'modeling'},
                                                        {'name': 'rig'},
                                                        {'name': 'shader'}],
                                           'name': 'publish'}],
                             'name': 'scenes'},
                            {'name': 'sound'},
                            {'children': [{'name': '3dPaintTextures'},
                                          {'name': 'environment'},
                                          {'name': 'imagePlane'},
                                          {'name': 'imageSequence'}],
                             'name': 'sourceimages'}],
               'name': 'maya'},
              {'children': [{'name': 'input'}, {'name': 'output'}],
               'name': 'nuke'},
              {'children': [{'name': 'photoshop'}, {'name': 'procreate'}],
               'name': 'paint_2D'},
              {'children': [{'name': 'mari'}, {'name': 'substance'}],
               'name': 'paint_3D'},
              {'name': 'preprod'},
              {'name': 'review'},
              {'name': 'sculpt'}]}


shot_template = {'name': 'assetName', 
 'children': [{'name': 'camera'},
              {'children': [{'name': 'abc'},
                            {'name': 'audio'},
                            {'name': 'comp'},
                            {'name': 'desk'},
                            {'name': 'flip'},
                            {'name': 'geo'},
                            {'name': 'hdz'},
                            {'name': 'render'},
                            {'name': 'scripts'},
                            {'name': 'sim'},
                            {'name': 'tex'},
                            {'name': 'video'},
                            {'name': 'workFiles'}],
               'name': 'houdini'},
              {'children': [{'children': [{'name': 'alembic'},
                                          {'name': 'bifrost'},
                                          {'name': 'nCache'},
                                          {'name': 'particles'}],
                             'name': 'cache'},
                            {'name': 'data'},
                            {'name': 'images'},
                            {'name': 'movies'},
                            {'children': [{'name': 'anim'},
                                          {'name': 'layout'},
                                          {'name': 'render'}],
                             'name': 'scenes'},
                            {'name': 'sound'},
                            {'children': [{'name': '3dPaintTextures'},
                                          {'name': 'environment'},
                                          {'name': 'imagePlane'},
                                          {'name': 'imageSequence'}],
                             'name': 'sourceimages'}],
               'name': 'maya'},
              {'children': [{'name': 'input'}, {'name': 'output'}],
               'name': 'nuke'}]}